/**
 * @link
 * https://genshin-impact.fandom.com/wiki/Artifact/Stats
 */

const ARTIFACT_ROLL_HP = 298.75
const ARTIFACT_ROLL_ATK = 19.45
const ARTIFACT_ROLL_DEF = 23.15
const ARTIFACT_ROLL_HP_PERCENT = 0.0583
const ARTIFACT_ROLL_ATK_PERCENT = 0.0583
const ARTIFACT_ROLL_DEF_PERCENT = 0.0729
const ARTIFACT_ROLL_EM = 23.31
const ARTIFACT_ROLL_ER = 0.0648
const ARTIFACT_ROLL_CR = 0.0389
const ARTIFACT_ROLL_CD = 0.0777

const MAIN_STAT_ATK_PERCENT = 0.466
const MAIN_STAT_DEF_PERCENT = 0.583
const MAIN_STAT_HEALING_BONUS = 0.359
const MAIN_STAT_HP_PERCENT = 0.466
const MAIN_STAT_EM = 186.5
const MAIN_STAT_ER = 0.518
const MAIN_STAT_DMG_BONUS = 0.466
const MAIN_STAT_CR = 0.311
const MAIN_STAT_CD = 0.622

module.exports = {
    ARTIFACT_ROLL_HP,
    ARTIFACT_ROLL_ATK,
    ARTIFACT_ROLL_DEF,
    ARTIFACT_ROLL_HP_PERCENT,
    ARTIFACT_ROLL_ATK_PERCENT,
    ARTIFACT_ROLL_DEF_PERCENT,
    ARTIFACT_ROLL_EM,
    ARTIFACT_ROLL_ER,
    ARTIFACT_ROLL_CR,
    ARTIFACT_ROLL_CD,

    MAIN_STAT_ATK_PERCENT,
    MAIN_STAT_DEF_PERCENT,
    MAIN_STAT_HEALING_BONUS,
    MAIN_STAT_HP_PERCENT,
    MAIN_STAT_EM,
    MAIN_STAT_ER,
    MAIN_STAT_DMG_BONUS,
    MAIN_STAT_CR,
    MAIN_STAT_CD,
}
